
import groupe_assignment.VehicleNodeClass;
import groupe_assignment.QueueInterface;
import groupe_assignment.WaitLine;
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Precious
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
 
    public GUI() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jL_serviceTime1 = new javax.swing.JLabel();
        jL_serviceTime2 = new javax.swing.JLabel();
        jBnt_Simulate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTxt_Prob = new javax.swing.JTextField();
        jTxt_Sv2 = new javax.swing.JTextField();
        jBtn_Reset = new javax.swing.JButton();
        jL_serviceTime3 = new javax.swing.JLabel();
        jTxt_Sv3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jL_serviceTime1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jL_serviceTime1.setLabelFor(jL_serviceTime1);
        jL_serviceTime1.setText("Arriving Probability (%)");

        jL_serviceTime2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jL_serviceTime2.setLabelFor(jL_serviceTime2);
        jL_serviceTime2.setText("Vehicle Service Time of Being  5 units");

        jBnt_Simulate.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jBnt_Simulate.setText("Simulate");
        jBnt_Simulate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnt_SimulateActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTxt_Prob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxt_ProbActionPerformed(evt);
            }
        });

        jTxt_Sv2.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTxt_Sv2InputMethodTextChanged(evt);
            }
        });
        jTxt_Sv2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxt_Sv2ActionPerformed(evt);
            }
        });

        jBtn_Reset.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jBtn_Reset.setText("Reset");
        jBtn_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_ResetActionPerformed(evt);
            }
        });

        jL_serviceTime3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jL_serviceTime3.setLabelFor(jL_serviceTime2);
        jL_serviceTime3.setText("Vehicle Service Time of Being  3 units");

        jTxt_Sv3.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jL_serviceTime2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTxt_Sv2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jL_serviceTime1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTxt_Prob, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 216, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBnt_Simulate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtn_Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jL_serviceTime3, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTxt_Sv3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_serviceTime1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxt_Prob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_serviceTime2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxt_Sv2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_serviceTime3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxt_Sv3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBnt_Simulate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtn_Reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBnt_SimulateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnt_SimulateActionPerformed
        // TODO add your handling code here:
        WaitLine vLine = new WaitLine();
        
         
        int cnt = 0;
        double ServceChance1 = Double.parseDouble(jTxt_Sv2.getText())/100;
        double Probability = Double.parseDouble(jTxt_Prob.getText())/100;
        ArrayList<String> Simulator_Feedback = new ArrayList<String>();
        ArrayList<String> FinalReport_Feedback = new ArrayList<String>();
        Simulator_Feedback = vLine.simulate(120,Probability, ServceChance1);
        
        
        
        while(cnt < Simulator_Feedback.size()){
            jTextArea1.append(Simulator_Feedback.get(cnt) + "\n" );
            System.out.println(Simulator_Feedback.get(cnt));
            cnt++;
        }
        jTextArea1.append("\n" );
        System.out.println("\n");
       cnt=0;
        FinalReport_Feedback = vLine.displayResults(120);
        while(cnt < FinalReport_Feedback.size()){
            jTextArea1.append(FinalReport_Feedback.get(cnt) + "\n" );
            
            System.out.println(FinalReport_Feedback.get(cnt));
            cnt++;
        }
        
    }//GEN-LAST:event_jBnt_SimulateActionPerformed

    private void jTxt_ProbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxt_ProbActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTxt_ProbActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        jTxt_Prob.setText("45");
        jTxt_Sv2.setText("35");
        jTxt_Sv3.setText("65");
    }//GEN-LAST:event_formWindowOpened

    private void jBtn_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_ResetActionPerformed
        // TODO add your handling code here:
        QueueInterface<String> q = new VehicleNodeClass<String>();
        jTxt_Prob.setText("45");
        jTxt_Sv2.setText("35");
        jTxt_Sv3.setText("65");
        jTextArea1.setText("");
        q.Clear();
    }//GEN-LAST:event_jBtn_ResetActionPerformed

    private void jTxt_Sv2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxt_Sv2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTxt_Sv2ActionPerformed

    private void jTxt_Sv2InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTxt_Sv2InputMethodTextChanged
        // TODO add your handling code here:
        
        jTxt_Sv2.setText("35");
        jTextArea1.setText("Work");
    }//GEN-LAST:event_jTxt_Sv2InputMethodTextChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBnt_Simulate;
    private javax.swing.JButton jBtn_Reset;
    private javax.swing.JLabel jL_serviceTime1;
    private javax.swing.JLabel jL_serviceTime2;
    private javax.swing.JLabel jL_serviceTime3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTxt_Prob;
    private javax.swing.JTextField jTxt_Sv2;
    private javax.swing.JTextField jTxt_Sv3;
    // End of variables declaration//GEN-END:variables
}
